### ISSUE TITLE
Does this still fully work?

### ISSUE THREAD

**Issue by funkytaco** [cliffhall/in-app-pro-shop#10]
Hi, thank you for your book.

I tried the code on Ropsten Testnet and while I do get the following

https://i.imgur.com/xZ4h0Ua.png

I am not sure how this is usable as a shop. Is it broken?

**Comment by cliffhall** [comment]
Hi there.

It isn't broken, your screenshot shows you were successful in creating a shop and some SKUs.

Now you need to integrate your front and/or back end with the contract to make sales. The goal of In-App Pro Shop is merely to help you get the blockchain part of a shop built and give you an admin UI for populating it with items and for withdrawing the revenue from sales. Or at least give you a model for building your own implementation.

Cheers, 
-=Cliff>

**Comment by funkytaco** [comment]
Hi, thanks Cliff.

Ah, I see, so this is more for transferring sales back to your wallet and not a front-end?

Since every item uses gas, I assume they are being stored on the blockchain? If so, how do I see that "Painting 1" is on the blockchain? I take it that is up for me to figure out from here?

If I wanted to store a file on IPFS, would that require more work, or just include some sort of node module and a few lines of code?

**Comment by cliffhall** [comment]
This is for setting up a shop on the blockchain, which has SKUs that define items that can be minted into real NFTs, for allowing people to buy those NFTs, and for splitting the income between a franchise owner and the shop owner. It is multi-tenant so multiple shops are supported. It is up to the shop owner to integrate with the contract. 

I built it initially as a 'side hustle' idea to see if I wanted to get into blockchain work. I found that I enjoyed it, but was skeptical that game companies would be integrating NFTs any time soon (this was a couple years back), so rather than try and run it as a franchise, I chose to document the arduous path to getting into blockchain development in a web series, then a book. 

The project still works and is sound, but the idea is that you'd take it and make it your own. Hopefully it would save a team some time getting this side of things built.

**Comment by funkytaco** [comment]
Ah, ok. So basically, I would need to integrate a wallet on a front-end, and somehow tie to the smart contracts? I guess I have more reading to do.

**Comment by cliffhall** [comment]
The app itself provides examples for implementing the wallet and contract communication using React, Redux, and web3.

You may prefer to do it with a different architecture / framework but this code can help you get acquainted with the process.


-=Cliff>
